### ISSUE TITLE
Can you please release the current master to a new version?

### ISSUE THREAD

**Issue by LutzStrobel** [migalons/angular-wdio-builder#7]
The current master uses updated versions of the dependencies. 
We use the version 1.0.2 with older dependencies wich causes errors on starting e2e tests.
There is an article unter stackoverflow (https://stackoverflow.com/questions/69903768/error-not-supported-keyword-id-use-id-for-schema-id-following-angular13), which means, that an updated version of this module could be useful.
So, please do it.
Thanx
the Luz

**Comment by migalons** [comment]
I’m having issues with my npmjs account. As soon as I recover it, I’ll push
it.

**Comment by LutzStrobel** [comment]
I tried to build it locally, but after load the zip and npm i, I get errors during build:
> @migalons/angular-wdio-builder@1.0.2 build
> tsc

node_modules/ajv/dist/types/json-schema.d.ts:1:92 - error TS1005: '?' expected.

1 declare type StrictNullChecksWrapper<Name extends string, Type> = undefined extends null ? `strictNullChecks must be true in tsconfig to use ${Name}` : Type;
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ajv/dist/types/json-schema.d.ts:1:151 - error TS1005: ';' expected.

1 declare type StrictNullChecksWrapper<Name extends string, Type> = undefined extends null ? `strictNullChecks must be true in tsconfig to use ${Name}` : Type;
                                                                           
What is wrong with it?
Can you help me?                                                                             ~

**Comment by migalons** [comment]
I've just merged a PR to upgrade those versions to support angular 14.

Can you try it to let me know if this fixed the issue?
